import Head from "next/head";
import Sidebar from "/components/Sidebar";
import Feed from "/components/Feed";
import RightBar from "/components/Rightbar";
import { HomeIcon, UserIcon, UserAddIcon } from "@heroicons/react/outline";
import Link from "next/link";

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto max-h-screen relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-9 ">
        <Sidebar />
        <Feed />
        <RightBar />
      </main>
      <div className="sm:hidden flex w-full items-center justify-between px-2 fixed bottom-0 z-10 bg-white ">
        <Link href="/">
          <div
            className={`  cursor-pointer transition-all duration-300 rounded-full flex p-3 items-center space-x-4 text-lg hover:bg-gray-100 max-w-fit `}
          >
            <HomeIcon className="w-8 " />
            <h2 className=" hidden lg:inline">Anasayfa</h2>
          </div>
        </Link>
        <Link href="/login">
          <div
            className={` cursor-pointer transition-all duration-300 rounded-full flex p-3 items-center space-x-4 text-lg hover:bg-gray-100 max-w-fit `}
          >
            <UserIcon className="w-8 " />
            <h2 className="hidden lg:inline">Oturum Aç</h2>
          </div>
        </Link>
        <Link href="/register">
          <div
            className={`  cursor-pointer transition-all duration-300 rounded-full flex p-3 items-center space-x-4 text-lg hover:bg-gray-100 max-w-fit `}
          >
            <UserAddIcon className="w-8 " />
            <h2 className="hidden lg:inline">Kayıt Ol</h2>
          </div>
        </Link>
      </div>
    </div>
  );
}
